// generators/app/templates/dev/react/App.tsx
import * as React from "react";
import * as ReactDOM from "react-dom";

import { Home } from "./home/Home";

import <% if(cssPreprocessor == 'Stylus') { %>'./style.styl'<% } %><% if(cssPreprocessor == 'Less') { %>'./style.less'<% } %><% if(cssPreprocessor == 'Sass') { %>'./style.scss'<% } %>;

ReactDOM.render(<Home header="Humble electron generator" />, document.querySelector("electron-app"));

// generators/app/templates/dev/app/app.component.ts
import { Component } from '@angular/core';

import <% if(cssPreprocessor == 'Stylus') { %>'./app.component.styl'<% } %><% if(cssPreprocessor == 'Less') { %>'./app.component.less'<% } %><% if(cssPreprocessor == 'Sass') { %>'./app.component.scss'<% } %>;

@Component({
    selector: 'electron-app',
    template: <% if(templateEngine == true) { %>require('./app.component.pug')()<% } else { %> require('./app.component.html') <% } %>
})

export class AppComponent {

}

<div class="header">
	<h1>Humble electron generator</h1>
</div>

<div class="content">
	<router-outlet></router-outlet>
</div>
